/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: lib/layout-utils.ts
 - Purpose: Shared utilities and cross-cutting concerns.
 - Context: Implements cross-cutting helpers used by multiple features.
 - How it works: Collects stateless helpers for formatting, configuration, I/O, or integration.
 - Refactoring ideas: Consolidate overlapping utilities with consistent naming. | Add unit tests to validate tricky edge cases.
 - Security considerations: Guard external I/O and sanitize any deserialized inputs.
*/
export function updateContentLayout(value: "centered" | "full-width") {
  const target = document.querySelector('[data-slot="sidebar-inset"]');
  if (target) {
    target.setAttribute("data-content-layout", value);
  }
}

export function updateNavbarStyle(value: "sticky" | "scroll") {
  const target = document.querySelector("header[data-navbar-style]");
  if (target) {
    target.setAttribute("data-navbar-style", value);
  }
}
