/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: lib/session.ts
 - Purpose: Shared utilities and cross-cutting concerns.
 - Context: Implements cross-cutting helpers used by multiple features.
 - How it works: Collects stateless helpers for formatting, configuration, I/O, or integration. Uses: Next.js App Router.
 - External imports: iron-session, next/headers
 - Refactoring ideas: Consolidate overlapping utilities with consistent naming. | Add unit tests to validate tricky edge cases.
 - Security considerations: Guard external I/O and sanitize any deserialized inputs.
*/
import { getIronSession, IronSession } from "iron-session";
import { cookies } from "next/headers";

export interface SessionData {
  userId: string;
  email: string;
  name: string;
  isLoggedIn: boolean;
}

const sessionOptions = {
  password: process.env.BETTER_AUTH_SECRET!, // Reuse the existing secret
  cookieName: "lending-os-session",
  cookieOptions: {
    secure: process.env.NODE_ENV === "production",
    maxAge: 60 * 60 * 24 * 7, // 7 days
  },
};

export async function getSession(): Promise<IronSession<SessionData>> {
  return await getIronSession<SessionData>(await cookies(), sessionOptions);
}

export async function requireAuth(): Promise<SessionData> {
  const session = await getSession();
  
  if (!session.isLoggedIn || !session.userId) {
    throw new Error("Unauthorized");
  }
  
  return session;
}

