/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: lib/utils.ts
 - Purpose: Shared utilities and cross-cutting concerns.
 - Context: Implements cross-cutting helpers used by multiple features.
 - How it works: Collects stateless helpers for formatting, configuration, I/O, or integration.
 - External imports: clsx, tailwind-merge
 - Refactoring ideas: Consolidate overlapping utilities with consistent naming. | Add unit tests to validate tricky edge cases.
 - Security considerations: Guard external I/O and sanitize any deserialized inputs.
*/
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const getInitials = (str: string): string => {
  if (typeof str !== "string" || !str.trim()) return "?";

  return (
    str
      .trim()
      .split(/\s+/)
      .filter(Boolean)
      .map((word) => word[0])
      .join("")
      .toUpperCase() || "?"
  );
};

export function formatCurrency(
  amount: number,
  opts?: {
    currency?: string;
    locale?: string;
    minimumFractionDigits?: number;
    maximumFractionDigits?: number;
    noDecimals?: boolean;
  },
) {
  const { currency = "USD", locale = "en-US", minimumFractionDigits, maximumFractionDigits, noDecimals } = opts ?? {};

  const formatOptions: Intl.NumberFormatOptions = {
    style: "currency",
    currency,
    minimumFractionDigits: noDecimals ? 0 : minimumFractionDigits,
    maximumFractionDigits: noDecimals ? 0 : maximumFractionDigits,
  };

  return new Intl.NumberFormat(locale, formatOptions).format(amount);
}
