/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: app/api/v1/borrowers/[id]/route.ts
 - Purpose: HTTP route handlers for v1/borrowers/[id] (App Router API).
 - Context: Exposes server-side endpoints consumed by UI and external clients.
 - How it works: Exports HTTP method handlers (e.g., GET/POST) that validate input, call services, and return structured JSON responses. Uses: Next.js App Router.
 - External imports: next/server
 - Local imports: @/services/borrower.service, @/lib/session, @/lib/validation/borrowers, @/types/borrower
 - Refactoring ideas: Centralize input validation schemas and response helpers. | Enforce consistent error typing and status codes. | Consider rate limiting and per-user quotas.
 - Security considerations: Validate and sanitize all inputs; enforce authorization checks. | Avoid leaking sensitive fields in responses. | Consider rate limiting and audit logging.
*/
import { NextRequest, NextResponse } from "next/server";
import { BorrowerService } from "@/services/borrower.service";
import { requireAuth } from "@/lib/session";
import { updateBorrowerSchema } from "@/lib/validation/borrowers";
import type { UpdateBorrowerDTO } from "@/types/borrower";

/**
 * GET /api/v1/borrowers/[id]
 * Get a single borrower by ID
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    await requireAuth();

    const { id } = await params;
    const borrower = await BorrowerService.getBorrowerById(id);

    if (!borrower) {
      return NextResponse.json({ success: false, error: "Borrower not found" }, { status: 404 });
    }

    return NextResponse.json({
      success: true,
      data: borrower,
    });
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
    }

    console.error("Error fetching borrower:", error);
    return NextResponse.json({ success: false, error: "Internal server error" }, { status: 500 });
  }
}

/**
 * PATCH /api/v1/borrowers/[id]
 * Update a borrower
 */
export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    await requireAuth();

    const body = await request.json();

    // Validate with Zod
    const validationResult = updateBorrowerSchema.safeParse(body);
    if (!validationResult.success) {
      return NextResponse.json(
        {
          success: false,
          error: "Validation failed",
          details: validationResult.error.errors,
        },
        { status: 400 }
      );
    }

    const { id } = await params;
    const borrower = await BorrowerService.updateBorrower(id, validationResult.data);

    if (!borrower) {
      return NextResponse.json({ success: false, error: "Borrower not found" }, { status: 404 });
    }

    return NextResponse.json({
      success: true,
      data: borrower,
    });
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
    }

    console.error("Error updating borrower:", error);
    return NextResponse.json({ success: false, error: "Internal server error" }, { status: 500 });
  }
}

/**
 * DELETE /api/v1/borrowers/[id]
 * Delete a borrower
 */
export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    await requireAuth();

    const { id } = await params;
    const success = await BorrowerService.deleteBorrower(id);

    if (!success) {
      return NextResponse.json({ success: false, error: "Borrower not found" }, { status: 404 });
    }

    return NextResponse.json({
      success: true,
      message: "Borrower deleted successfully",
    });
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
    }

    console.error("Error deleting borrower:", error);
    return NextResponse.json({ success: false, error: "Internal server error" }, { status: 500 });
  }
}

