/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: db/schema/index.ts
 - Purpose: Database schema and table definitions (Drizzle ORM).
 - Context: Defines and interacts with the persistence layer.
 - How it works: Declares tables, columns, and relationships; migrations align the database to these definitions.
 - Refactoring ideas: Add indexes for frequent query paths. | Enforce constraints at the schema level. | Document migration rationale and rollback plans.
 - Security considerations: Constrain data with not-null and foreign keys. | Protect PII with encryption at rest where needed.
*/
export * from "./users";
export * from "./organizations";
export * from "./borrowers";
export * from "./lenders";
export * from "./properties";
export * from "./roles";
export * from "./loans";
export * from "./loan_documents";
export * from "./loan_notes";
export * from "./relationships";
export * from "./payments";
export * from "./draws";

