/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: db/schema/loan_documents.ts
 - Purpose: Database schema and table definitions (Drizzle ORM).
 - Context: Defines and interacts with the persistence layer.
 - How it works: Declares tables, columns, and relationships; migrations align the database to these definitions.
 - External imports: drizzle-orm/pg-core
 - Local imports: ./loans
 - Refactoring ideas: Add indexes for frequent query paths. | Enforce constraints at the schema level. | Document migration rationale and rollback plans.
 - Security considerations: Constrain data with not-null and foreign keys. | Protect PII with encryption at rest where needed.
*/
import { pgTable, text, timestamp, uuid, pgEnum } from "drizzle-orm/pg-core";
import { loans } from "./loans";

export const loanDocumentTypeEnum = pgEnum("loan_document_type", [
  "application",
  "appraisal",
  "title",
  "insurance",
  "closing_docs",
  "other",
]);

export const loanDocuments = pgTable("loan_documents", {
  id: uuid("id").defaultRandom().primaryKey(),
  loanId: uuid("loan_id")
    .notNull()
    .references(() => loans.id, { onDelete: "cascade" }),
  documentType: loanDocumentTypeEnum("document_type").notNull(),
  fileName: text("file_name").notNull(),
  fileUrl: text("file_url").notNull(),
  fileSize: text("file_size"),
  uploadedBy: text("uploaded_by"),
  uploadedAt: timestamp("uploaded_at").defaultNow().notNull(),
});

