/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: db/schema/properties.ts
 - Purpose: Database schema and table definitions (Drizzle ORM).
 - Context: Defines and interacts with the persistence layer.
 - How it works: Declares tables, columns, and relationships; migrations align the database to these definitions.
 - External imports: drizzle-orm/pg-core
 - Local imports: ./organizations
 - Refactoring ideas: Add indexes for frequent query paths. | Enforce constraints at the schema level. | Document migration rationale and rollback plans.
 - Security considerations: Constrain data with not-null and foreign keys. | Protect PII with encryption at rest where needed.
*/
import { pgTable, text, timestamp, uuid, numeric, pgEnum, jsonb } from "drizzle-orm/pg-core";
import { organizations } from "./organizations";

export const propertyTypeEnum = pgEnum("property_type", [
  "single_family",
  "multi_family",
  "commercial",
  "land",
]);

export const properties = pgTable("properties", {
  id: uuid("id").defaultRandom().primaryKey(),
  organizationId: uuid("organization_id")
    .notNull()
    .references(() => organizations.id, { onDelete: "cascade" }),
  
  // Location
  address: text("address").notNull(),
  city: text("city").notNull(),
  state: text("state").notNull(),
  zip: text("zip").notNull(),
  
  // Property details
  propertyType: propertyTypeEnum("property_type").notNull(),
  occupancy: text("occupancy"), // v2: 'owner_occupied' | 'tenant_occupied' | 'vacant'
  
  // Valuation
  estimatedValue: numeric("estimated_value", { precision: 14, scale: 2 }), // v2
  purchasePrice: numeric("purchase_price", { precision: 15, scale: 2 }).notNull(),
  appraisedValue: numeric("appraised_value", { precision: 15, scale: 2 }),
  appraisalDate: timestamp("appraisal_date", { withTimezone: true }),
  
  // Construction/rehab
  rehabBudget: numeric("rehab_budget", { precision: 14, scale: 2 }), // v2
  
  // Photos stored as JSONB array of {key, url}
  photos: jsonb("photos").$type<Array<{ key: string; url?: string }>>(), // v2
  
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

export const propertyPhotos = pgTable("property_photos", {
  id: uuid("id").defaultRandom().primaryKey(),
  propertyId: uuid("property_id")
    .notNull()
    .references(() => properties.id, { onDelete: "cascade" }),
  fileUrl: text("file_url").notNull(),
  caption: text("caption"),
  uploadedAt: timestamp("uploaded_at").defaultNow().notNull(),
});

