/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: app/api/v1/borrowers/route.ts
 - Purpose: HTTP route handlers for v1/borrowers (App Router API).
 - Context: Exposes server-side endpoints consumed by UI and external clients.
 - How it works: Exports HTTP method handlers (e.g., GET/POST) that validate input, call services, and return structured JSON responses. Uses: Next.js App Router, Zod.
 - External imports: next/server, zod
 - Local imports: @/services/borrower.service, @/lib/session, @/lib/validation/borrowers, @/types/borrower
 - Refactoring ideas: Centralize input validation schemas and response helpers. | Enforce consistent error typing and status codes. | Consider rate limiting and per-user quotas.
 - Security considerations: Validate and sanitize all inputs; enforce authorization checks. | Avoid leaking sensitive fields in responses. | Consider rate limiting and audit logging.
*/
import { NextRequest, NextResponse } from "next/server";
import { ZodError } from "zod";
import { BorrowerService } from "@/services/borrower.service";
import { requireAuth } from "@/lib/session";
import { createBorrowerSchema } from "@/lib/validation/borrowers";
import type { CreateBorrowerDTO } from "@/types/borrower";

/**
 * GET /api/v1/borrowers
 * Get all borrowers for the authenticated user's organization
 */
export async function GET(request: NextRequest) {
  try {
    const session = await requireAuth();

    const borrowers = await BorrowerService.getBorrowersByOrganization(session.userId);

    return NextResponse.json({
      success: true,
      data: borrowers,
      count: borrowers.length,
    });
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
    }

    console.error("Error fetching borrowers:", error);
    return NextResponse.json({ success: false, error: "Internal server error" }, { status: 500 });
  }
}

/**
 * POST /api/v1/borrowers
 * Create a new borrower
 */
export async function POST(request: NextRequest) {
  try {
    const session = await requireAuth();
    const body = await request.json();

    // Validate with Zod
    const validationResult = createBorrowerSchema.safeParse(body);
    if (!validationResult.success) {
      return NextResponse.json(
        {
          success: false,
          error: "Validation failed",
          details: validationResult.error.errors,
        },
        { status: 400 }
      );
    }

    const borrowerData: CreateBorrowerDTO = {
      ...validationResult.data,
      organizationId: session.userId,
    };

    const borrower = await BorrowerService.createBorrower(borrowerData);

    return NextResponse.json(
      {
        success: true,
        data: borrower,
      },
      { status: 201 }
    );
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
    }

    console.error("Error creating borrower:", error);
    return NextResponse.json({ success: false, error: "Internal server error" }, { status: 500 });
  }
}

