/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: services/collateral.service.ts
 - Purpose: Domain service for data access and business logic.
 - Context: Mediates between API routes/UI and the database layer.
 - How it works: Implements domain logic and orchestrates database calls with clear input/output types. Uses: Drizzle ORM.
 - External imports: drizzle-orm
 - Local imports: @/db/client, @/db/schema, @/types/collateral
 - Refactoring ideas: Define transaction boundaries explicitly. | Return typed result objects instead of throwing. | Isolate DB access behind repository helpers.
 - Security considerations: Use parameterized queries to prevent injection. | Do not log sensitive data. | Handle concurrency and race conditions explicitly.
*/
import { eq } from "drizzle-orm";
import { db } from "@/db/client";
import { collateral } from "@/db/schema";
import type { Collateral, CreateCollateralDTO, UpdateCollateralDTO } from "@/types/collateral";

export class CollateralService {
  /**
   * Create collateral record
   */
  static async createCollateral(data: CreateCollateralDTO): Promise<Collateral> {
    const [record] = await db
      .insert(collateral)
      .values({
        loanId: data.loanId,
        lienPosition: data.lienPosition || null,
        description: data.description || null,
        drawSchedule: data.drawSchedule || null,
      })
      .returning();

    return record as Collateral;
  }

  /**
   * Get collateral by loan ID
   */
  static async getByLoanId(loanId: string): Promise<Collateral | null> {
    const [record] = await db
      .select()
      .from(collateral)
      .where(eq(collateral.loanId, loanId))
      .limit(1);

    return (record as Collateral) || null;
  }

  /**
   * Update collateral
   */
  static async updateCollateral(
    loanId: string,
    data: UpdateCollateralDTO
  ): Promise<Collateral | null> {
    const updateData: Record<string, unknown> = {
      updatedAt: new Date(),
    };

    if (data.lienPosition !== undefined) updateData.lienPosition = data.lienPosition;
    if (data.description !== undefined) updateData.description = data.description;
    if (data.drawSchedule !== undefined) updateData.drawSchedule = data.drawSchedule;

    const [updated] = await db
      .update(collateral)
      .set(updateData)
      .where(eq(collateral.loanId, loanId))
      .returning();

    return (updated as Collateral) || null;
  }

  /**
   * Delete collateral
   */
  static async deleteCollateral(loanId: string): Promise<boolean> {
    await db.delete(collateral).where(eq(collateral.loanId, loanId));
    return true;
  }
}

