/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: components/loan/loan-status-badge.tsx
 - Purpose: Reusable React UI component loan-status-badge.tsx.
 - Context: Composes UI from smaller primitives and domain data.
 - How it works: Renders UI based on props and context; defers side effects to hooks.
 - Local imports: @/components/ui/badge, @/types/loan, @/lib/loan-state-machine
 - Refactoring ideas: Split complex components into smaller units. | Memoize expensive subtrees and handlers. | Extract data fetching into hooks/services.
 - Security considerations: Avoid dangerouslySetInnerHTML; sanitize any HTML content. | Do not embed secrets or tokens in client code. | Harden forms against CSRF where applicable.
*/
import { Badge } from "@/components/ui/badge";
import { LoanStatus } from "@/types/loan";
import { getStatusLabel, getStatusVariant } from "@/lib/loan-state-machine";

interface LoanStatusBadgeProps {
  status: LoanStatus;
  className?: string;
}

export function LoanStatusBadge({ status, className }: LoanStatusBadgeProps) {
  return (
    <Badge variant={getStatusVariant(status)} className={className}>
      {getStatusLabel(status)}
    </Badge>
  );
}

