/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: app/api/v1/lenders/route.ts
 - Purpose: HTTP route handlers for v1/lenders (App Router API).
 - Context: Exposes server-side endpoints consumed by UI and external clients.
 - How it works: Exports HTTP method handlers (e.g., GET/POST) that validate input, call services, and return structured JSON responses. Uses: Next.js App Router.
 - External imports: next/server
 - Local imports: @/services/lender.service, @/lib/session, @/lib/validation/lenders, @/types/lender
 - Refactoring ideas: Centralize input validation schemas and response helpers. | Enforce consistent error typing and status codes. | Consider rate limiting and per-user quotas.
 - Security considerations: Validate and sanitize all inputs; enforce authorization checks. | Avoid leaking sensitive fields in responses. | Consider rate limiting and audit logging.
*/
import { NextRequest, NextResponse } from "next/server";
import { LenderService } from "@/services/lender.service";
import { requireAuth } from "@/lib/session";
import { createLenderSchema } from "@/lib/validation/lenders";
import type { CreateLenderDTO } from "@/types/lender";

/**
 * GET /api/v1/lenders
 * Get all lenders for the authenticated user's organization
 */
export async function GET(request: NextRequest) {
  try {
    const session = await requireAuth();

    const lenders = await LenderService.getLendersByOrganization(session.userId);

    return NextResponse.json({
      success: true,
      data: lenders,
      count: lenders.length,
    });
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
    }

    console.error("Error fetching lenders:", error);
    return NextResponse.json({ success: false, error: "Internal server error" }, { status: 500 });
  }
}

/**
 * POST /api/v1/lenders
 * Create a new lender
 */
export async function POST(request: NextRequest) {
  try {
    const session = await requireAuth();
    const body = await request.json();

    // Validate with Zod
    const validationResult = createLenderSchema.safeParse(body);
    if (!validationResult.success) {
      return NextResponse.json(
        {
          success: false,
          error: "Validation failed",
          details: validationResult.error.errors,
        },
        { status: 400 }
      );
    }

    const lenderData: CreateLenderDTO = {
      ...validationResult.data,
      organizationId: session.userId,
    };

    const lender = await LenderService.createLender(lenderData);

    return NextResponse.json(
      {
        success: true,
        data: lender,
      },
      { status: 201 }
    );
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
    }

    console.error("Error creating lender:", error);
    return NextResponse.json({ success: false, error: "Internal server error" }, { status: 500 });
  }
}

