/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: app/api/v1/loans/[loanId]/lenders/route.ts
 - Purpose: HTTP route handlers for v1/loans/[loanId]/lenders (App Router API).
 - Context: Exposes server-side endpoints consumed by UI and external clients.
 - How it works: Exports HTTP method handlers (e.g., GET/POST) that validate input, call services, and return structured JSON responses. Uses: Next.js App Router.
 - External imports: next/server
 - Local imports: @/services/loan.service, @/types/loan
 - Refactoring ideas: Centralize input validation schemas and response helpers. | Enforce consistent error typing and status codes. | Consider rate limiting and per-user quotas.
 - Security considerations: Validate and sanitize all inputs; enforce authorization checks. | Avoid leaking sensitive fields in responses. | Consider rate limiting and audit logging.
*/
import { NextRequest, NextResponse } from "next/server";
import { LoanService } from "@/services/loan.service";
import { LenderRole } from "@/types/loan";

/**
 * POST /api/v1/loans/:loanId/lenders
 * Add a participant lender to an existing loan (syndication)
 */
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ loanId: string }> }
) {
  try {
    const { loanId } = await params;
    const body = await request.json();

    const { lenderId, percentage } = body;

    if (!lenderId) {
      return NextResponse.json(
        { success: false, error: "lenderId is required" },
        { status: 400 }
      );
    }

    if (percentage === undefined || percentage === null) {
      return NextResponse.json(
        { success: false, error: "percentage is required" },
        { status: 400 }
      );
    }

    // Validate percentage
    if (percentage < 0 || percentage > 100) {
      return NextResponse.json(
        { success: false, error: "percentage must be between 0 and 100" },
        { status: 400 }
      );
    }

    const relationship = await LoanService.addParticipantLender(
      loanId,
      lenderId,
      percentage
    );

    return NextResponse.json({
      success: true,
      data: relationship,
    });
  } catch (error) {
    console.error("Error adding participant lender:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Failed to add participant lender",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}

/**
 * GET /api/v1/loans/:loanId/lenders
 * Get all lenders for a loan
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ loanId: string }> }
) {
  try {
    const { loanId } = await params;

    const lenders = await LoanService.getLoanLenders(loanId);

    return NextResponse.json({
      success: true,
      data: lenders,
    });
  } catch (error) {
    console.error("Error fetching loan lenders:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Failed to fetch lenders",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}

