/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: app/api/v1/inspections/[inspectionId]/complete/route.ts
 - Purpose: HTTP route handlers for v1/inspections/[inspectionId]/complete (App Router API).
 - Context: Exposes server-side endpoints consumed by UI and external clients.
 - How it works: Exports HTTP method handlers (e.g., GET/POST) that validate input, call services, and return structured JSON responses. Uses: Next.js App Router.
 - External imports: next/server
 - Local imports: @/services/inspection.service
 - Refactoring ideas: Centralize input validation schemas and response helpers. | Enforce consistent error typing and status codes. | Consider rate limiting and per-user quotas.
 - Security considerations: Validate and sanitize all inputs; enforce authorization checks. | Avoid leaking sensitive fields in responses. | Consider rate limiting and audit logging.
*/
import { NextRequest, NextResponse } from "next/server";
import { InspectionService } from "@/services/inspection.service";

/**
 * PUT /api/v1/inspections/:inspectionId/complete
 * Complete an inspection with results
 */
export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ inspectionId: string }> }
) {
  try {
    const { inspectionId } = await params;
    const body = await request.json();

    // Validate required fields
    if (body.workCompletionPercentage === undefined || body.qualityRating === undefined) {
      return NextResponse.json(
        {
          success: false,
          error: "Missing required fields: workCompletionPercentage, qualityRating",
        },
        { status: 400 }
      );
    }

    const inspection = await InspectionService.completeInspection(inspectionId, {
      workCompletionPercentage: body.workCompletionPercentage,
      qualityRating: body.qualityRating,
      safetyCompliant: body.safetyCompliant ?? true,
      findings: body.findings,
      recommendations: body.recommendations,
      photos: body.photos,
      signatures: body.signatures,
      weatherConditions: body.weatherConditions,
      equipmentUsed: body.equipmentUsed,
      inspectionDurationMinutes: body.inspectionDurationMinutes,
    });

    return NextResponse.json({
      success: true,
      data: inspection,
    });
  } catch (error) {
    console.error("Error completing inspection:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Failed to complete inspection",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}

