/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: app/api/v1/ai/forecast/route.ts
 - Purpose: HTTP route handlers for v1/ai/forecast (App Router API).
 - Context: Exposes server-side endpoints consumed by UI and external clients.
 - How it works: Exports HTTP method handlers (e.g., GET/POST) that validate input, call services, and return structured JSON responses. Uses: Next.js App Router.
 - External imports: next/server
 - Local imports: @/lib/ai/utils, @/types/forecast
 - Refactoring ideas: Centralize input validation schemas and response helpers. | Enforce consistent error typing and status codes. | Consider rate limiting and per-user quotas.
 - Security considerations: Validate and sanitize all inputs; enforce authorization checks. | Avoid leaking sensitive fields in responses. | Consider rate limiting and audit logging.
*/
import { NextRequest, NextResponse } from "next/server";
import { aiEnhancedForecast } from "@/lib/ai/utils";
import type { ForecastInput } from "@/types/forecast";

/**
 * POST /api/v1/ai/forecast
 * Enhanced AI-powered loan forecast with risk assessment
 */
export async function POST(request: NextRequest) {
  try {
    const body: ForecastInput = await request.json();

    // Validate required fields
    if (!body.principal || !body.rate || !body.termMonths || !body.category) {
      return NextResponse.json(
        {
          success: false,
          error: "Missing required fields: principal, rate, termMonths, category",
        },
        { status: 400 }
      );
    }

    const forecast = await aiEnhancedForecast(body);

    return NextResponse.json({
      success: true,
      data: forecast,
    });
  } catch (error) {
    console.error("Error generating AI forecast:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Failed to generate AI forecast",
      },
      { status: 500 }
    );
  }
}
