"use client";

/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: hooks/useLoans.ts
 - Purpose: Custom React hook useLoans.
 - Context: Encapsulates reusable view or data-fetching logic.
 - How it works: Abstracts stateful logic and effects behind a stable API for components. Uses: React Client Component, TanStack Query.
 - External imports: @tanstack/react-query
 - Refactoring ideas: Stabilize dependencies and memoize returned values. | Expose minimal surface area with clear naming.
 - Security considerations: Prevent accidental exposure of secrets to the client side.
*/
import { useQuery } from "@tanstack/react-query";

/**
 * Fetch all loans for the authenticated user's organization
 */
export const useLoans = () => {
  return useQuery({
    queryKey: ["loans"],
    queryFn: async () => {
      const response = await fetch("/api/v1/loans");
      if (!response.ok) {
        throw new Error("Failed to fetch loans");
      }
      const data = await response.json();
      return data.data;
    },
  });
};
