/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: db/client 2.ts
 - Purpose: Database utilities, clients, and scripts.
 - Context: Defines and interacts with the persistence layer.
 - How it works: Initializes DB clients and runs maintenance scripts (migrate/seed/clear).
 - External imports: drizzle-orm/postgres-js, postgres
 - Local imports: ./schema
 - Refactoring ideas: Add indexes for frequent query paths. | Enforce constraints at the schema level. | Document migration rationale and rollback plans.
 - Security considerations: Constrain data with not-null and foreign keys. | Protect PII with encryption at rest where needed.
*/
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import * as schema from "./schema";

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL environment variable is not set");
}

// Create postgres connection
const connection = postgres(process.env.DATABASE_URL, {
  max: 10,
  idle_timeout: 20,
  connect_timeout: 10,
});

// Create drizzle instance
export const db = drizzle(connection, { schema });

// Export types
export type Database = typeof db;

