/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: types/lender.ts
 - Purpose: Shared TypeScript types and interfaces.
 - Context: Ensures type safety across modules and features.
 - How it works: Provides shared data contracts to prevent type drift across modules.
 - Refactoring ideas: Prefer discriminated unions over stringly-typed fields. | Use readonly where mutation is not intended.
 - Security considerations: Mark sensitive fields and avoid accidental serialization.
*/
export enum EntityType {
  INDIVIDUAL = "individual",
  COMPANY = "company",
  FUND = "fund",
  IRA = "ira", // v2 addition
}

export interface Lender {
  id: string;
  organizationId: string;
  name: string;
  entityType: EntityType;
  contactEmail: string;
  contactPhone: string | null; // v2 addition
  totalCommitted: string;
  totalDeployed: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateLenderDTO {
  organizationId: string;
  name: string;
  entityType: EntityType | "individual" | "company" | "fund" | "ira";
  contactEmail: string;
  contactPhone?: string; // v2 addition
  totalCommitted?: number | string;
  totalDeployed?: number | string;
}

export interface UpdateLenderDTO {
  name?: string;
  entityType?: EntityType | "individual" | "company" | "fund" | "ira";
  contactEmail?: string;
  contactPhone?: string | null; // v2 addition
  totalCommitted?: number | string;
  totalDeployed?: number | string;
}

