/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: types/loan-note 2.ts
 - Purpose: Shared TypeScript types and interfaces.
 - Context: Ensures type safety across modules and features.
 - How it works: Provides shared data contracts to prevent type drift across modules.
 - Refactoring ideas: Prefer discriminated unions over stringly-typed fields. | Use readonly where mutation is not intended.
 - Security considerations: Mark sensitive fields and avoid accidental serialization.
*/
export interface LoanNote {
  id: string;
  loanId: string;
  content: string;
  createdBy: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateLoanNoteDTO {
  loanId: string;
  content: string;
  createdBy: string;
}

export interface UpdateLoanNoteDTO {
  content: string;
}

