/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: types/property 2.ts
 - Purpose: Shared TypeScript types and interfaces.
 - Context: Ensures type safety across modules and features.
 - How it works: Provides shared data contracts to prevent type drift across modules.
 - Refactoring ideas: Prefer discriminated unions over stringly-typed fields. | Use readonly where mutation is not intended.
 - Security considerations: Mark sensitive fields and avoid accidental serialization.
*/
export enum PropertyType {
  SINGLE_FAMILY = "single_family",
  MULTI_FAMILY = "multi_family",
  COMMERCIAL = "commercial",
  LAND = "land",
}

export interface Property {
  id: string;
  organizationId: string; // v2 addition
  address: string;
  city: string;
  state: string;
  zip: string;
  propertyType: PropertyType;
  purchasePrice: string;
  appraisedValue: string | null;
  appraisalDate: Date | null;
  
  // v2 additions
  occupancy: "owner_occupied" | "tenant_occupied" | "vacant" | null;
  estimatedValue: string | null;
  rehabBudget: string | null;
  photos: Array<{ key: string; url?: string }> | null; // JSONB
  
  createdAt: Date;
  updatedAt: Date;
}

export interface CreatePropertyDTO {
  organizationId: string; // v2 addition
  address: string;
  city: string;
  state: string;
  zip: string;
  propertyType: PropertyType;
  purchasePrice: number | string;
  appraisedValue?: number | string;
  appraisalDate?: Date;
  
  // v2 additions
  occupancy?: "owner_occupied" | "tenant_occupied" | "vacant";
  estimatedValue?: number | string;
  rehabBudget?: number | string;
  photos?: Array<{ key: string; url?: string }>;
}

export interface UpdatePropertyDTO {
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  propertyType?: PropertyType;
  purchasePrice?: number | string;
  appraisedValue?: number | string | null;
  appraisalDate?: Date | null;
  
  // v2 additions
  occupancy?: "owner_occupied" | "tenant_occupied" | "vacant" | null;
  estimatedValue?: number | string | null;
  rehabBudget?: number | string | null;
  photos?: Array<{ key: string; url?: string }> | null;
}

export interface PropertyPhoto {
  id: string;
  propertyId: string;
  fileUrl: string;
  caption: string | null;
  uploadedAt: Date;
}

