"use client";

/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: app/not-found.tsx
 - Purpose: Module not-found.tsx supporting application features.
 - Context: Supports a feature area and composes with adjacent modules.
 - How it works: Provides supporting logic composed by higher-level modules. Uses: React Client Component, Next.js App Router.
 - External imports: next/link
 - Local imports: @/components/ui/button
 - Refactoring ideas: Align with module boundaries and update tests accordingly.
 - Security considerations: Follow least-privilege and avoid leaking implementation details.
*/
import Link from "next/link";

import { Button } from "@/components/ui/button";

export default function NotFound() {
  return (
    <div className="flex h-dvh flex-col items-center justify-center space-y-2 text-center">
      <h1 className="text-2xl font-semibold">Page not found.</h1>
      <p className="text-muted-foreground">The page you are looking for could not be found.</p>
      <Link replace href="/dashboard/default">
        <Button variant="outline">Go back home</Button>
      </Link>
    </div>
  );
}
