/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: config/app-config.ts
 - Purpose: Module app-config.ts supporting application features.
 - Context: Supports a feature area and composes with adjacent modules.
 - How it works: Provides supporting logic composed by higher-level modules.
 - Local imports: ../../package.json
 - Refactoring ideas: Align with module boundaries and update tests accordingly.
 - Security considerations: Follow least-privilege and avoid leaking implementation details.
*/
import packageJson from "../../package.json";

const currentYear = new Date().getFullYear();

export const APP_CONFIG = {
  name: "Lending OS",
  version: packageJson.version,
  copyright: `© ${currentYear}, Lending OS.`,
  meta: {
    title: "Lending OS - Modern Loan Management Platform",
    description:
      "Lending OS is a next-generation loan management platform for private and hard-money lenders. Manage the full loan lifecycle—from origination to payoff—with a modern, intuitive interface built on Next.js 16, Drizzle ORM, and Shadcn UI.",
  },
};
