/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: app/api/v1/properties/route.ts
 - Purpose: HTTP route handlers for v1/properties (App Router API).
 - Context: Exposes server-side endpoints consumed by UI and external clients.
 - How it works: Exports HTTP method handlers (e.g., GET/POST) that validate input, call services, and return structured JSON responses. Uses: Next.js App Router.
 - External imports: next/server
 - Local imports: @/services/property.service, @/lib/session, @/types/property
 - Refactoring ideas: Centralize input validation schemas and response helpers. | Enforce consistent error typing and status codes. | Consider rate limiting and per-user quotas.
 - Security considerations: Validate and sanitize all inputs; enforce authorization checks. | Avoid leaking sensitive fields in responses. | Consider rate limiting and audit logging.
*/
import { NextRequest, NextResponse } from "next/server";
import { PropertyService } from "@/services/property.service";
import { requireAuth } from "@/lib/session";
import type { CreatePropertyDTO } from "@/types/property";

/**
 * GET /api/v1/properties
 * Get all properties
 */
export async function GET(request: NextRequest) {
  try {
    await requireAuth();

    const properties = await PropertyService.getProperties();

    return NextResponse.json({
      success: true,
      data: properties,
      count: properties.length,
    });
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
    }

    console.error("Error fetching properties:", error);
    return NextResponse.json({ success: false, error: "Internal server error" }, { status: 500 });
  }
}

/**
 * POST /api/v1/properties
 * Create a new property
 */
export async function POST(request: NextRequest) {
  try {
    await requireAuth();
    const body: CreatePropertyDTO = await request.json();

    // Validate required fields
    if (!body.address || !body.city || !body.state || !body.zip || !body.propertyType || !body.purchasePrice) {
      return NextResponse.json(
        {
          success: false,
          error: "Missing required fields: address, city, state, zip, propertyType, purchasePrice",
        },
        { status: 400 }
      );
    }

    const property = await PropertyService.createProperty(body);

    return NextResponse.json(
      {
        success: true,
        data: property,
      },
      { status: 201 }
    );
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
    }

    console.error("Error creating property:", error);
    return NextResponse.json({ success: false, error: "Internal server error" }, { status: 500 });
  }
}

