/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: app/api/v1/ai/document-process/route.ts
 - Purpose: HTTP route handlers for v1/ai/document-process (App Router API).
 - Context: Exposes server-side endpoints consumed by UI and external clients.
 - How it works: Exports HTTP method handlers (e.g., GET/POST) that validate input, call services, and return structured JSON responses. Uses: Next.js App Router, Zod.
 - External imports: next/server, zod
 - Local imports: @/lib/ai/utils
 - Refactoring ideas: Centralize input validation schemas and response helpers. | Enforce consistent error typing and status codes. | Consider rate limiting and per-user quotas.
 - Security considerations: Validate and sanitize all inputs; enforce authorization checks. | Avoid leaking sensitive fields in responses. | Consider rate limiting and audit logging.
*/
import { NextRequest, NextResponse } from "next/server";
import { processLoanDocument } from "@/lib/ai/utils";
import { z } from "zod";

const documentProcessingSchema = z.object({
  documentText: z.string().min(1),
  documentType: z.enum([
    'loan_application',
    'financial_statement',
    'tax_return',
    'bank_statement',
    'property_appraisal',
    'insurance_document',
    'contract',
    'other'
  ]),
});

/**
 * POST /api/v1/ai/document-process
 * AI-powered document processing and data extraction
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { documentText, documentType } = documentProcessingSchema.parse(body);

    const result = await processLoanDocument(documentText, documentType);

    if (!result.success) {
      return NextResponse.json(
        {
          success: false,
          error: result.error,
        },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      data: result.object,
    });
  } catch (error) {
    console.error("Error processing document:", error);
    
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        {
          success: false,
          error: "Invalid request format",
          details: error.errors,
        },
        { status: 400 }
      );
    }

    return NextResponse.json(
      {
        success: false,
        error: "Failed to process document",
      },
      { status: 500 }
    );
  }
}
