/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: app/api/v1/draws/[drawId]/route.ts
 - Purpose: HTTP route handlers for v1/draws/[drawId] (App Router API).
 - Context: Exposes server-side endpoints consumed by UI and external clients.
 - How it works: Exports HTTP method handlers (e.g., GET/POST) that validate input, call services, and return structured JSON responses. Uses: Next.js App Router.
 - External imports: next/server
 - Local imports: @/services/draw.service
 - Refactoring ideas: Centralize input validation schemas and response helpers. | Enforce consistent error typing and status codes. | Consider rate limiting and per-user quotas.
 - Security considerations: Validate and sanitize all inputs; enforce authorization checks. | Avoid leaking sensitive fields in responses. | Consider rate limiting and audit logging.
*/
import { NextRequest, NextResponse } from "next/server";
import { DrawService } from "@/services/draw.service";

/**
 * GET /api/v1/draws/:drawId
 * Get draw by ID
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ drawId: string }> }
) {
  try {
    const { drawId } = await params;

    const draw = await DrawService.getDraw(drawId);

    if (!draw) {
      return NextResponse.json(
        { success: false, error: "Draw not found" },
        { status: 404 }
      );
    }

    return NextResponse.json({
      success: true,
      data: draw,
    });
  } catch (error) {
    console.error("Error fetching draw:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Failed to fetch draw",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}

/**
 * PUT /api/v1/draws/:drawId
 * Update draw details
 */
export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ drawId: string }> }
) {
  try {
    const { drawId } = await params;
    const body = await request.json();

    const draw = await DrawService.updateDraw(drawId, {
      amountRequested: body.amountRequested,
      workDescription: body.workDescription,
      budgetLineItem: body.budgetLineItem,
      contractorName: body.contractorName,
      contractorContact: body.contractorContact,
      notes: body.notes,
    });

    return NextResponse.json({
      success: true,
      data: draw,
    });
  } catch (error) {
    console.error("Error updating draw:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Failed to update draw",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}

/**
 * DELETE /api/v1/draws/:drawId
 * Delete a draw
 */
export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ drawId: string }> }
) {
  try {
    const { drawId } = await params;

    await DrawService.deleteDraw(drawId);

    return NextResponse.json({
      success: true,
      message: "Draw deleted successfully",
    });
  } catch (error) {
    console.error("Error deleting draw:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Failed to delete draw",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}

