/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: middleware.ts
 - Purpose: Edge middleware that runs before requests.
 - Context: Supports a feature area and composes with adjacent modules.
 - How it works: Executes at the edge per request for routing, auth checks, or response rewriting. Uses: Next.js App Router.
 - External imports: next/server
 - Refactoring ideas: Align with module boundaries and update tests accordingly.
 - Security considerations: Follow least-privilege and avoid leaking implementation details.
*/
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

export async function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Get the session cookie
  const sessionCookie = request.cookies.get("lending-os-session");

  const isAuthPage = pathname.startsWith("/auth");
  const isDashboardPage = pathname.startsWith("/dashboard");
  const isAuthenticated = !!sessionCookie;

  // Redirect authenticated users away from auth pages
  if (isAuthPage && isAuthenticated) {
    return NextResponse.redirect(new URL("/dashboard", request.url));
  }

  // Redirect unauthenticated users to login from protected pages
  if (isDashboardPage && !isAuthenticated) {
    const loginUrl = new URL("/auth/v1/login", request.url);
    loginUrl.searchParams.set("from", pathname);
    return NextResponse.redirect(loginUrl);
  }

  return NextResponse.next();
}

export const config = {
  matcher: [
    "/((?!api|_next/static|_next/image|favicon.ico).*)",
  ],
};
