/*
 File Header (auto-generated by scripts/add-file-headers.ts)
 - File: app/(main)/dashboard/portfolio/page.tsx
 - Purpose: Next.js page for /dashboard/portfolio.
 - Context: Participates in the app router hierarchy for end-user navigation.
 - How it works: Defines a React component rendered by the app router; fetches and displays data via services/hooks.
 - Local imports: ./_components/loan-summary, ./_components/delinquency-summary, ./_components/portfolio-overview, ./_components/recent-activity
 - Refactoring ideas: Split complex components into smaller units. | Memoize expensive subtrees and handlers. | Extract data fetching into hooks/services.
 - Security considerations: Avoid dangerouslySetInnerHTML; sanitize any HTML content. | Do not embed secrets or tokens in client code. | Harden forms against CSRF where applicable.
*/
import { LoanSummary } from "./_components/loan-summary";
import { DelinquencySummary } from "./_components/delinquency-summary";
import { PortfolioOverview } from "./_components/portfolio-overview";
import { RecentActivity } from "./_components/recent-activity";

export default function Page() {
  return (
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
      <div className="flex flex-col gap-4 lg:col-span-1">
        <LoanSummary />
      </div>

      <div className="flex flex-col gap-4 lg:col-span-2">
        <div className="flex-1">
          <PortfolioOverview />
        </div>
        <div className="grid flex-1 grid-cols-1 gap-4 *:data-[slot=card]:shadow-xs md:grid-cols-2">
          <DelinquencySummary />
          <RecentActivity />
        </div>
      </div>
    </div>
  );
}
